### ISSUE TITLE
Unable to train due to: Trainer.__init__() got an unexpected keyword argument 'gpus'

### ISSUE THREAD

**Issue by KaiTang2** [cidcom/satellite-cloud-removal-dip#3]
I encountered the following error while runing the trainer. Also there is a warning in Cell 10 which I am too sure why. Appreciate any help.
![image](https://github.com/cidcom/satellite-cloud-removal-dip/assets/33851010/66c8a648-4e88-4ab1-bf18-db10b98712c7)

**Comment by mikonvergence** [comment]
Hi @KaiTang2, this is just a matter of the updated interface in pytorch lightning, I don't know which version you are using but it must be a more recent one.

Current documentation for the latest version:
https://lightning.ai/docs/pytorch/stable/accelerators/gpu_basic.html

It seems that setting `devices=[0]` instead of `gpus=[0]` should do the trick if you're using that version of lightning.
